name: Release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - run: yarn install --immutable

      - run: yarn test

      - run: yarn build

      - name: Prune dev dependencies
        run: yarn install --production --ignore-scripts

      - name: Create release tarball
        run: |
          tar czvf /tmp/local-addon-wordpress-supercharged.tar.gz \
            --exclude="./src" \
            --exclude="./versions" \
            --exclude="./.github" \
            --exclude="./.git" \
            --exclude="./coverage" \
            --exclude=".DS_Store" \
            --exclude=".env" \
            --exclude=".eslintcache" \
            --exclude="*.log" \
            --exclude="./tsconfig.json" \
            --exclude="./jest.config.js" \
            --exclude="./CHANGELOG.md" \
            --exclude="./README.md" \
            --exclude="./yarn.lock" \
            --exclude="./.yarn" \
            --exclude="./.gitignore" \
            --exclude="./gifs" \
            .

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/local-addon-wordpress-supercharged.tar.gz
